name: "Test"
on:
  pull_request:
jobs:
  test-nix:
    name: 'Nix'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.4
      with:
        submodules: recursive

    - name: Install Nix
      uses: cachix/install-nix-action@v12

    - name: Install Cachix
      uses: cachix/cachix-action@v8
      with:
        name: runtimeverification
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: Build
      run: nix-build -A k

    - name: Check shell
      run: nix-shell --run "echo OK"

    - name: Run integration tests
      run: nix-build test.nix
