name: "Test"
on:
  pull_request:
jobs:
  test-nix:
    name: 'Nix'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2.3.4
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: 'Install Nix'
        uses: cachix/install-nix-action@v12

      - name: 'Install Cachix'
        uses: cachix/cachix-action@v8
        with:
          name: runtimeverification
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

      # Check that the pinned Maven dependencies are up-to-date.
      # We cannot update them in the pull request job.
      - name: 'Check for changed Maven dependencies'
        run: |
          ./nix/update-maven.sh
          if [ ! $(git status --porcelain | wc -l) -eq 0 ]; then
            echo "Found dirty files:"
            git status --porcelain
            exit 1
          fi

      - name: 'Build K Framework'
        run: nix-build -A k -A llvm-backend -A haskell-backend

      - name: 'Check development environment'
        run: nix-shell --run "echo OK"

  # Update README.md if this job changes.
  test-nix-install:
    name: 'Nix: Install'
    needs: test-nix
    strategy:
      matrix:
        os: [ubuntu-latest]
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2.3.4
        with:
          # Check out pull request HEAD instead of merge commit.
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive

      - name: 'Install prerequisites'
        run: |
          bash <(curl -L https://nixos.org/nix/install)
          . $HOME/.nix-profile/etc/profile.d/nix.sh
          nix-env -iA cachix -f https://cachix.org/api/v1/install
          cachix use runtimeverification

      - name: 'Install K Framework'
        run: |
          . $HOME/.nix-profile/etc/profile.d/nix.sh
          nix-env -f . -i -A k -A haskell-backend -A llvm-backend
